spring:
  application:
    name: Eureka-Server
eureka:
  instance:
    hostname: localhost
---
spring:
  profiles: Eureka-Server1

server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/

---
spring:
  profiles: Eureka-Server2

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

