spring:
  application:
    name: service-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,health

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

---
spring:
  profiles: service-consumer1
server:
  port: 8080
---
spring:
  profiles: service-consumer2
server:
  port: 8081