server:
  port: 8080

spring:
  application:
    name: service-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,health,info