server:
  port: 8080

spring:
  application:
    name: service-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,health,info

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000