server:
  port: 8880

#属性文件地址，只要指定文件夹的路径
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs/
#使用本地属性文件
  profiles:
    active: native

#使用Git地址
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: file://${user.home}/config-repo