spring:
  application:
    name: Eureka-Server

---
spring:
  profiles: Eureka-Server1

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://username:password@${eureka.instance.hostname}:8762/eureka/

---
spring:
  profiles: Eureka-Server2

server:
  port: 8762

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://username:password@${eureka.instance.hostname}:8761/eureka/

