spring:
  application:
    name: service-client

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,health,info

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

---
spring:
  profiles: service-client1

server:
  port: 8080
management:
  server:
    port: 9080
eureka:
  instance:
    metadata-map:
      management.port: ${management.server.port}
---
spring:
  profiles: service-client2


server:
  port: 8081
management:
  server:
    port: 9081
#  servlet:
#    context-path: /ribbon
#eureka:
#  instance:
#    home-page-url-path: /ribbon
#    prefer-ip-address: true