server:
  port: 8761

spring:
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/
