spring:
  application:
    name: service-instance

eureka:
  client:
    serviceUrl:
      defaultZone: http://username:password@localhost:8761/eureka/,http://username:password@localhost:8762/eureka/

---
spring:
  profiles: service-instance1

server:
  port: 8000

---
spring:
  profiles: service-instance2

server:
  port: 8001
