eureka:
  client:
    serviceUrl:
      defaultZone: http://username:password@localhost:8761/eureka/, http://username:password@localhost:8762/eureka/
server:
  port: 8080
spring:
  application:
    name: service-client