eureka:
  client:
    serviceUrl:
      defaultZone: http://username:password@localhost:8761/eureka/, http://username:password@localhost:8762/eureka/
server:
  port: 8080
spring:
  application:
    name: service-client

service-instance:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

#service-instance:
#  ribbon:
#    listOfServers: localhost:8000