server:
  port: 8000
spring:
  application:
    name: service-instance
eureka:
  instance:
      client:
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/